accessWidener	v1	named
accessible	method	net/minecraft/server/BlockDispenser	dispense	(Lnet/minecraft/server/World;Lnet/minecraft/server/BlockPosition;)V
accessible	method	net/minecraft/server/BlockJukeBox	dropRecord	(Lnet/minecraft/server/World;Lnet/minecraft/server/BlockPosition;Lnet/minecraft/server/IBlockData;)V
accessible	method	net/minecraft/server/BlockRedstoneWire	getPower	(Lnet/minecraft/server/World;Lnet/minecraft/server/BlockPosition;I)I
accessible	field	net/minecraft/server/Chunk	world	Lnet/minecraft/server/World;
accessible	field	net/minecraft/server/Chunk	heightMap	[I
accessible	field	net/minecraft/server/Chunk	tileEntities	Ljava/util/Map;
accessible	field	net/minecraft/server/Chunk	entitySlices	[Lnet/minecraft/server/EntitySlice;
accessible	field	net/minecraft/server/ChunkProviderServer	emptyChunk	Lnet/minecraft/server/Chunk;
accessible	field	net/minecraft/server/ChunkProviderServer	chunkProvider	Lnet/minecraft/server/IChunkProvider;
accessible	field	net/minecraft/server/ChunkProviderServer	world	Lnet/minecraft/server/WorldServer;
accessible	method	net/minecraft/server/ChunkProviderServer	loadChunk	(II)Lnet/minecraft/server/Chunk;
accessible	method	net/minecraft/server/ChunkProviderServer	saveChunkNOP	(Lnet/minecraft/server/Chunk;)V
accessible	method	net/minecraft/server/ChunkProviderServer	saveChunk	(Lnet/minecraft/server/Chunk;)V
accessible	field	net/minecraft/server/ContainerDispenser	items	Lnet/minecraft/server/IInventory;
accessible	field	net/minecraft/server/CraftingManager	recipes	Ljava/util/List;
accessible	method	net/minecraft/server/CraftingManager	<init>	()V
accessible	field	net/minecraft/server/DedicatedServer	propertyManager	Lnet/minecraft/server/PropertyManager;
accessible	field	net/minecraft/server/Entity	fireTicks	I
accessible	method	net/minecraft/server/Entity	setSize	(FF)V
accessible	field	net/minecraft/server/EntityArmorStand	headPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	bodyPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	leftArmPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	rightArmPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	leftLegPose	Lnet/minecraft/server/Vector3f;
accessible	field	net/minecraft/server/EntityArmorStand	rightLegPose	Lnet/minecraft/server/Vector3f;
accessible	method	net/minecraft/server/EntityArmorStand	setSmall	(Z)V
accessible	method	net/minecraft/server/EntityArmorStand	setGravity	(Z)V
accessible	method	net/minecraft/server/EntityArmorStand	setArms	(Z)V
accessible	method	net/minecraft/server/EntityArmorStand	setBasePlate	(Z)V
accessible	field	net/minecraft/server/EntityArrow	knockbackStrength	I
accessible	field	net/minecraft/server/EntityEnderDragon	target	Lnet/minecraft/server/Entity;
accessible	field	net/minecraft/server/EntityExperienceOrb	value	I
accessible	field	net/minecraft/server/EntityFireworks	expectedLifespan	I
accessible	field	net/minecraft/server/EntityGuardian	goalRandomStroll	Lnet/minecraft/server/PathfinderGoalRandomStroll;
accessible	method	net/minecraft/server/EntityMonster	initAttributes	()V
accessible	field	net/minecraft/server/EntityHanging	blockPosition	Lnet/minecraft/server/BlockPosition;
accessible	method	net/minecraft/server/EntityHanging	setDirection	(Lnet/minecraft/server/EnumDirection;)V
accessible	field	net/minecraft/server/EntityHorse	attributeJumpStrength	Lnet/minecraft/server/IAttribute;
accessible	field	net/minecraft/server/EntityHorse	inventoryChest	Lnet/minecraft/server/InventoryHorseChest;
accessible	method	net/minecraft/server/EntityHorse	loadChest	()V
accessible	field	net/minecraft/server/EntityHuman	sleeping	Z
accessible	field	net/minecraft/server/EntityHuman	sleepTicks	I
accessible	method	net/minecraft/server/EntityHuman	closeInventory	()V
accessible	field	net/minecraft/server/EntityInsentient	goalSelector	Lnet/minecraft/server/PathfinderGoalSelector;
accessible	field	net/minecraft/server/EntityInsentient	targetSelector	Lnet/minecraft/server/PathfinderGoalSelector;
accessible	field	net/minecraft/server/EntityInsentient	dropChances	[F
accessible	field	net/minecraft/server/EntityInsentient	canPickUpLoot	Z
accessible	field	net/minecraft/server/EntityInsentient	persistent	Z
accessible	field	net/minecraft/server/EntityItem	pickupDelay	I
accessible	field	net/minecraft/server/EntityLiving	combatTracker	Lnet/minecraft/server/CombatTracker;
accessible	field	net/minecraft/server/EntityLiving	effects	Ljava/util/Map;
accessible	field	net/minecraft/server/EntityLiving	killer	Lnet/minecraft/server/EntityHuman;
accessible	field	net/minecraft/server/EntityLiving	lastDamage	F
accessible	field	net/minecraft/server/EntityLiving	updateEffects	Z
accessible	field	net/minecraft/server/EntityLiving	lastDamager	Lnet/minecraft/server/EntityLiving;
accessible	field	net/minecraft/server/EntityLiving	hurtTimestamp	I
accessible	field	net/minecraft/server/EntityPigZombie	angerLevel	I
accessible	field	net/minecraft/server/EntityPlayer	removeQueue	Ljava/util/List;
accessible	field	net/minecraft/server/EntityPlayer	lastSentExp	I
accessible	field	net/minecraft/server/EntityPlayer	invulnerableTicks	I
accessible	field	net/minecraft/server/EntityPotion	item	Lnet/minecraft/server/ItemStack;
accessible	field	net/minecraft/server/EntityProjectile	shooter	Lnet/minecraft/server/EntityLiving;
accessible	field	net/minecraft/server/EntityProjectile	shooterName	Ljava/lang/String;
accessible	method	net/minecraft/server/EntitySlime	setSize	(I)V
accessible	field	net/minecraft/server/EntityTracker	trackedEntities	Lnet/minecraft/server/IntHashMap;
accessible	field	net/minecraft/server/EntityVillager	inventory	Lnet/minecraft/server/InventorySubcontainer;
accessible	field	net/minecraft/server/Explosion	source	Lnet/minecraft/server/Entity;
accessible	field	net/minecraft/server/FoodMetaData	foodLevel	I
accessible	field	net/minecraft/server/FoodMetaData	saturationLevel	F
accessible	field	net/minecraft/server/FoodMetaData	exhaustionLevel	F
accessible	field	net/minecraft/server/InventoryLargeChest	left	Lnet/minecraft/server/ITileInventory;
accessible	field	net/minecraft/server/InventoryLargeChest	right	Lnet/minecraft/server/ITileInventory;
accessible	field	net/minecraft/server/EntityPlayer	containerCounter	I
accessible	method	net/minecraft/server/EntityPlayer	nextContainerCounter ()V
accessible	field	net/minecraft/server/InventorySubcontainer	items	[Lnet/minecraft/server/ItemStack;
accessible	method	net/minecraft/server/JsonListEntry	getKey	()Ljava/lang/Object;
accessible	field	net/minecraft/server/MobSpawnerAbstract	spawnDelay	I
accessible	method	net/minecraft/server/MobSpawnerAbstract	getMobName	()Ljava/lang/String;
accessible	field	net/minecraft/server/NetworkManager	channel	Lio/netty/channel/Channel;
accessible	field	net/minecraft/server/PacketHandshakingInSetProtocol	hostname	Ljava/lang/String;
accessible	field	net/minecraft/server/PacketHandshakingInSetProtocol	port	I
accessible	field	net/minecraft/server/PacketPlayOutBlockChange	block	Lnet/minecraft/server/IBlockData;
accessible	field	net/minecraft/server/PacketPlayOutSpawnPosition	position	Lnet/minecraft/server/BlockPosition;
accessible	field	net/minecraft/server/PlayerAbilities	flySpeed	F
accessible	field	net/minecraft/server/PlayerAbilities	walkSpeed	F
accessible	field	net/minecraft/server/PlayerList	players	Ljava/util/List;
accessible	field	net/minecraft/server/PlayerList	playerFileData	Lnet/minecraft/server/IPlayerFileData;
accessible	method	net/minecraft/server/PlayerList	sendScoreboard	(Lnet/minecraft/server/ScoreboardServer;Lnet/minecraft/server/EntityPlayer;)V
accessible	field	net/minecraft/server/PropertyManager	properties	Ljava/util/Properties;
accessible	field	net/minecraft/server/RecipesFurnace	recipes	Ljava/util/Map;
accessible	field	net/minecraft/server/Slot	index	I
accessible	field	net/minecraft/server/TileEntityBanner	color	I
accessible	field	net/minecraft/server/TileEntityBanner	patterns	Lnet/minecraft/server/NBTTagList;
accessible	field	net/minecraft/server/TileEntityBrewingStand	brewTime	I
accessible	field	net/minecraft/server/TileEntityFurnace	burnTime	I
accessible	field	net/minecraft/server/TileEntityFurnace	cookTime	I
accessible	field	net/minecraft/server/TileEntitySign	isEditable	Z
accessible	field	net/minecraft/server/WorldServer	tracker	Lnet/minecraft/server/EntityTracker;
extendable	method	net/minecraft/server/BlockDispenser	dispense	(Lnet/minecraft/server/World;Lnet/minecraft/server/BlockPosition;)V
extendable	method	net/minecraft/server/BlockJukeBox	dropRecord	(Lnet/minecraft/server/World;Lnet/minecraft/server/BlockPosition;Lnet/minecraft/server/IBlockData;)V
extendable	method	net/minecraft/server/BlockRedstoneWire	getPower	(Lnet/minecraft/server/World;Lnet/minecraft/server/BlockPosition;I)I
mutable	field	net/minecraft/server/Chunk	world	Lnet/minecraft/server/World;
mutable	field	net/minecraft/server/Chunk	heightMap	[I
mutable	field	net/minecraft/server/Chunk	tileEntities	Ljava/util/Map;
mutable	field	net/minecraft/server/Chunk	entitySlices	[Lnet/minecraft/server/EntitySlice;
mutable	field	net/minecraft/server/ChunkProviderServer	emptyChunk	Lnet/minecraft/server/Chunk;
mutable	field	net/minecraft/server/ChunkProviderServer	chunkProvider	Lnet/minecraft/server/IChunkProvider;
mutable	field	net/minecraft/server/ChunkProviderServer	world	Lnet/minecraft/server/WorldServer;
extendable	method	net/minecraft/server/ChunkProviderServer	loadChunk	(II)Lnet/minecraft/server/Chunk;
extendable	method	net/minecraft/server/ChunkProviderServer	saveChunkNOP	(Lnet/minecraft/server/Chunk;)V
extendable	method	net/minecraft/server/ChunkProviderServer	saveChunk	(Lnet/minecraft/server/Chunk;)V
mutable	field	net/minecraft/server/ContainerDispenser	items	Lnet/minecraft/server/IInventory;
mutable	field	net/minecraft/server/CraftingManager	recipes	Ljava/util/List;
extendable	method	net/minecraft/server/CraftingManager	<init>	()V
mutable	field	net/minecraft/server/DedicatedServer	propertyManager	Lnet/minecraft/server/PropertyManager;
mutable	field	net/minecraft/server/Entity	fireTicks	I
extendable	method	net/minecraft/server/Entity	setSize	(FF)V
mutable	field	net/minecraft/server/EntityArmorStand	headPose	Lnet/minecraft/server/Vector3f;
mutable	field	net/minecraft/server/EntityArmorStand	bodyPose	Lnet/minecraft/server/Vector3f;
mutable	field	net/minecraft/server/EntityArmorStand	leftArmPose	Lnet/minecraft/server/Vector3f;
mutable	field	net/minecraft/server/EntityArmorStand	rightArmPose	Lnet/minecraft/server/Vector3f;
mutable	field	net/minecraft/server/EntityArmorStand	leftLegPose	Lnet/minecraft/server/Vector3f;
mutable	field	net/minecraft/server/EntityArmorStand	rightLegPose	Lnet/minecraft/server/Vector3f;
extendable	method	net/minecraft/server/EntityArmorStand	setSmall	(Z)V
extendable	method	net/minecraft/server/EntityArmorStand	setGravity	(Z)V
extendable	method	net/minecraft/server/EntityArmorStand	setArms	(Z)V
extendable	method	net/minecraft/server/EntityArmorStand	setBasePlate	(Z)V
mutable	field	net/minecraft/server/EntityArrow	knockbackStrength	I
mutable	field	net/minecraft/server/EntityEnderDragon	target	Lnet/minecraft/server/Entity;
mutable	field	net/minecraft/server/EntityExperienceOrb	value	I
mutable	field	net/minecraft/server/EntityFireworks	expectedLifespan	I
mutable	field	net/minecraft/server/EntityGuardian	goalRandomStroll	Lnet/minecraft/server/PathfinderGoalRandomStroll;
extendable	method	net/minecraft/server/EntityMonster	initAttributes	()V
mutable	field	net/minecraft/server/EntityHanging	blockPosition	Lnet/minecraft/server/BlockPosition;
extendable	method	net/minecraft/server/EntityHanging	setDirection	(Lnet/minecraft/server/EnumDirection;)V
mutable	field	net/minecraft/server/EntityHorse	attributeJumpStrength	Lnet/minecraft/server/IAttribute;
mutable	field	net/minecraft/server/EntityHorse	inventoryChest	Lnet/minecraft/server/InventoryHorseChest;
extendable	method	net/minecraft/server/EntityHorse	loadChest	()V
mutable	field	net/minecraft/server/EntityHuman	sleeping	Z
mutable	field	net/minecraft/server/EntityHuman	sleepTicks	I
extendable	method	net/minecraft/server/EntityHuman	closeInventory	()V
mutable	field	net/minecraft/server/EntityInsentient	goalSelector	Lnet/minecraft/server/PathfinderGoalSelector;
mutable	field	net/minecraft/server/EntityInsentient	targetSelector	Lnet/minecraft/server/PathfinderGoalSelector;
mutable	field	net/minecraft/server/EntityInsentient	dropChances	[F
mutable	field	net/minecraft/server/EntityInsentient	canPickUpLoot	Z
mutable	field	net/minecraft/server/EntityInsentient	persistent	Z
mutable	field	net/minecraft/server/EntityItem	pickupDelay	I
mutable	field	net/minecraft/server/EntityLiving	combatTracker	Lnet/minecraft/server/CombatTracker;
mutable	field	net/minecraft/server/EntityLiving	effects	Ljava/util/Map;
mutable	field	net/minecraft/server/EntityLiving	killer	Lnet/minecraft/server/EntityHuman;
mutable	field	net/minecraft/server/EntityLiving	lastDamage	F
mutable	field	net/minecraft/server/EntityLiving	updateEffects	Z
mutable	field	net/minecraft/server/EntityLiving	lastDamager	Lnet/minecraft/server/EntityLiving;
mutable	field	net/minecraft/server/EntityLiving	hurtTimestamp	I
mutable	field	net/minecraft/server/EntityPigZombie	angerLevel	I
mutable	field	net/minecraft/server/EntityPlayer	removeQueue	Ljava/util/List;
mutable	field	net/minecraft/server/EntityPlayer	lastSentExp	I
mutable	field	net/minecraft/server/EntityPlayer	invulnerableTicks	I
mutable	field	net/minecraft/server/EntityPotion	item	Lnet/minecraft/server/ItemStack;
mutable	field	net/minecraft/server/EntityProjectile	shooter	Lnet/minecraft/server/EntityLiving;
mutable	field	net/minecraft/server/EntityProjectile	shooterName	Ljava/lang/String;
extendable	method	net/minecraft/server/EntitySlime	setSize	(I)V
mutable	field	net/minecraft/server/EntityTracker	trackedEntities	Lnet/minecraft/server/IntHashMap;
mutable	field	net/minecraft/server/EntityVillager	inventory	Lnet/minecraft/server/InventorySubcontainer;
mutable	field	net/minecraft/server/Explosion	source	Lnet/minecraft/server/Entity;
mutable	field	net/minecraft/server/FoodMetaData	foodLevel	I
mutable	field	net/minecraft/server/FoodMetaData	saturationLevel	F
mutable	field	net/minecraft/server/FoodMetaData	exhaustionLevel	F
mutable	field	net/minecraft/server/InventoryLargeChest	left	Lnet/minecraft/server/ITileInventory;
mutable	field	net/minecraft/server/InventoryLargeChest	right	Lnet/minecraft/server/ITileInventory;
mutable	field	net/minecraft/server/InventorySubcontainer	items	[Lnet/minecraft/server/ItemStack;
extendable	method	net/minecraft/server/JsonListEntry	getKey	()Ljava/lang/Object;
mutable	field	net/minecraft/server/MobSpawnerAbstract	spawnDelay	I
extendable	method	net/minecraft/server/MobSpawnerAbstract	getMobName	()Ljava/lang/String;
mutable	field	net/minecraft/server/NetworkManager	channel	Lio/netty/channel/Channel;
mutable	field	net/minecraft/server/PacketHandshakingInSetProtocol	hostname	Ljava/lang/String;
mutable	field	net/minecraft/server/PacketHandshakingInSetProtocol	port	I
mutable	field	net/minecraft/server/PacketPlayOutBlockChange	block	Lnet/minecraft/server/IBlockData;
mutable	field	net/minecraft/server/PacketPlayOutSpawnPosition	position	Lnet/minecraft/server/BlockPosition;
mutable	field	net/minecraft/server/PlayerAbilities	flySpeed	F
mutable	field	net/minecraft/server/PlayerAbilities	walkSpeed	F
mutable	field	net/minecraft/server/PlayerList	players	Ljava/util/List;
mutable	field	net/minecraft/server/PlayerList	playerFileData	Lnet/minecraft/server/IPlayerFileData;
extendable	method	net/minecraft/server/PlayerList	sendScoreboard	(Lnet/minecraft/server/ScoreboardServer;Lnet/minecraft/server/EntityPlayer;)V
mutable	field	net/minecraft/server/PropertyManager	properties	Ljava/util/Properties;
mutable	field	net/minecraft/server/RecipesFurnace	recipes	Ljava/util/Map;
mutable	field	net/minecraft/server/Slot	index	I
mutable	field	net/minecraft/server/TileEntityBanner	color	I
mutable	field	net/minecraft/server/TileEntityBanner	patterns	Lnet/minecraft/server/NBTTagList;
mutable	field	net/minecraft/server/TileEntityBrewingStand	brewTime	I
mutable	field	net/minecraft/server/TileEntityFurnace	burnTime	I
mutable	field	net/minecraft/server/TileEntityFurnace	cookTime	I
mutable	field	net/minecraft/server/TileEntitySign	isEditable	Z
mutable	field	net/minecraft/server/WorldServer	tracker	Lnet/minecraft/server/EntityTracker;
